### ISSUE TITLE
sudo cleanup for coins-cli

### ISSUE THREAD

**Issue by zombieprocess** [cdaringe/coins-cli#21]
## Current behavior 

This should work without having to do anything with `sudo`:

```
$ coins services status
[sudo] password for jragle: [sudo] password for jragle: [sudo] password for jragle: [sudo] password for jragle: 
```

`sudo` should be dropped from commands being wrapped by the `coins-cli` tool.

## Expected behavior 

Usage for *escalated* privileges should be of the form, following best practices:

        sudo coins services restart

`sudo` itself is providing the *escalated* privileges. The tool is providing what the tasks are done while having the *escalated* privileges.

**Comment by cdaringe** [comment]
you should work without having to do sudo! ;)

**Comment by zombieprocess** [comment]
HAH!
